Orchestrator/Orchestrator/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('OrchestratorApp.urls')),
    path('admin/', admin.site.urls),
]

# patch('reportApp', include('ReportApp.urls'))

Orchestrator/OrchestratorApp/urls.py
from django.urls import path

from . import views

app_name = 'OrchestratorApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('recon/', views.recon_view, name='recon'),
    path('workspaces/', views.show_workspaces, name='workspaces'),
    path('workspaces/<str:target_name>', views.show_workspace, name='workspace'),
    path('vulnerabilities', views.show_vulns, name='vulnerabilities'),
    path('vulnerabilities/<str:target_name>', views.show_project_vulns, name='project_vulns'),
    path('slack_in', views.slack_input, name='slack_in'),
    path('vulnerability_scan/', views.vuln_scan_view, name='vulnerability_scan'),
    path('one_shot_scan',views.one_shot_scan,name='one_shot_scan')
]

Orchestrator/OrchestratorApp/models.py
from django.db import models


# Create your models here.
class ReconProfile(models.Model):
    name = models.CharField(max_length=30)
    scan_mode = models.CharField(max_length=30)
    project = models.CharField(max_length=30)
    target = models.CharField(max_length=30)

Orchestrator/OrchestratorApp/forms.py
from django.forms import ModelForm
from django import forms
from .src.mongo import mongo
from .src import constants
from .src.redmine import redmine

LANGUAGE_CHOICES = [
	(constants.LANGUAGE_ENGLISH, 'English'),
	(constants.LANGUAGE_SPANISH, 'Spanish')
]

REPORT_CHOICES = [
	('F', 'Final'),
	('S', 'Status')
]

SCAN_CHOICES = [
	('existing_target', 'Existing Target'),
	('new_target', 'New target (Recon and security scan)'),
	('single_target', 'Scan against one url (With http/https)'),
	('file_target', 'Input file (Urls with http/https)'),
	('file_ip', 'Input file (Ips)')
]


class ReconForm(forms.Form):
	target = forms.CharField(label='Enter target', max_length=100)


class VulnerabilityScanForm(forms.Form):
	### Scan type selection
	scan_type = forms.CharField(label='Select scan type', widget=forms.Select(choices=SCAN_CHOICES,
	attrs={'onchange':'enable_scan_type_div(\'id_scan_type\')'}))
	## div_name = scan_choice_div
	## When a choice is selected, it will become required
	existing_targets = mongo.get_targets()
	existing_targets_list = list()
	for available_target in existing_targets:
		existing_targets_list.append((available_target, available_target))
	# div_name = existing_target_choice_div
	existing_target_choice = forms.CharField(label='Select existing target', 
		widget=forms.Select(choices=existing_targets_list), required=False)
	# div_name = new_target_choice_div
	new_target_choice = forms.CharField(label='New target', required=False)
	# div_name = single_target_choice_div
	single_target_choice = forms.CharField(label='New url (http/https)', required=False)
	# div_name = file_target_choice_div
	input_file_name = forms.FileField(label='Input file', required=False)
	# div_name = file_ip_target_choice_div
	input_ip_file_name = forms.FileField(label='Input file', required=False)

	use_active_modules = forms.BooleanField(required=False, initial=True, label='Invasive modules',
											help_text= "Enables intrusive nmap scripts (SSH/FTP/Default login)")
	use_nessus_scan = forms.BooleanField(required=False, initial=True, label='Nessus scan',
											help_text= "Launchs a Black Box nessus scan")
	use_acunetix_scan = forms.BooleanField(required=False, initial=True, label='Acunetix scan',
											help_text= "Launchs a Black Box acunetix scan")
	### Email selection
	checkbox_email = forms.BooleanField(label='Email notification ', required=False, initial=False,
	 widget=forms.CheckboxInput(attrs={"onchange":'enable_checkbox_div(\'id_checkbox_email\', \'email_div\' )'}))
	## div_name = email_div
	email = forms.CharField(label='Enter email here: ', required=False)

	### Report selection
	checkbox_report = forms.BooleanField(label='Report (requires email) ', required=False, initial=False,
	 widget=forms.CheckboxInput(attrs={"onchange":'enable_checkbox_div(\'id_checkbox_report\', \'report_div\' )'}))
	## div_name = report_div
	report_type = forms.CharField(label='Select report type', widget=forms.Select(choices=REPORT_CHOICES), required=False)
	selected_language = forms.CharField(label='Select language', widget=forms.Select(choices=LANGUAGE_CHOICES), required=False)
	
	### Redmine information
	### This will be disabled atm until UI is changed
	checkbox_redmine = forms.BooleanField(label='Redmine ', required=False, initial=False,
	 widget=forms.CheckboxInput(attrs={"onchange":'enable_checkbox_div(\'id_checkbox_redmine\', \'redmine_div\' )'}),
	 help_text='Only projects that have the user included will appear. Same applies to users for selection')

	REDMINE_PROJ_CHOICES = redmine.get_project_names()
	redmine_project = forms.CharField(label='Redmine project', widget=forms.Select(choices=REDMINE_PROJ_CHOICES), required=False)
	redmine_users = redmine.get_users()
	assigned_users = forms.MultipleChoiceField(widget=forms.SelectMultiple, choices=redmine_users,
											   label='Assigned to', help_text='Provide only 1 user',
											   required=False)
	watcher_users = forms.MultipleChoiceField(widget=forms.SelectMultiple, choices=redmine_users,
											   label='Watchers', help_text='1 or more users',
											   required=False)

Orchestrator/OrchestratorApp/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, FileResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .forms import VulnerabilityScanForm, ReconForm

from .src.mongo import mongo
from .src.slack import slack_receiver
from .src.recon import recon_handler
from .src.comms import download
from .src.reporting import reporting
from .src.security import vuln_scan_handler

from Orchestrator.settings import slack_web_client,redmine_client

import json
import os
import uuid

def index(request):
    return render(request, 'Orchestrator/base.html')


#### RECON ####
def show_workspaces(request):
    target = mongo.get_targets()
    return render(request, 'Orchestrator/workspaces_view.html', {'object_list': target})


def show_workspace(request, target_name):
    resources = mongo.get_workspace_resources(target_name)
    if request.method == 'POST':
        response = download.get_workspace_csv(request.path, resources)
        return response
    return render(request, 'Orchestrator/single_workspace_view.html', {'object_list': resources})


def recon_view(request):
    if request.method == 'POST':
        form = ReconForm(request.POST)
        if form.is_valid():
            target_name = form.cleaned_data['target']
            recon_handler.handle_recon(target_name)
            return redirect('/')
    form = ReconForm()
    return render(request, 'Orchestrator/recon_view.html', {'form': form})


#### BASELINE ####
def show_vulns(request):
    target = mongo.get_targets()
    return render(request, 'Orchestrator/vulns_view.html', {'object_list': target})


def show_project_vulns(request, target_name):
    resources = mongo.get_vulns_from_target(target_name)
    if request.method == 'POST':
        response = download.get_workspace_csv(request.path, resources)
        return response
    return render(request, 'Orchestrator/single_vulns_view.html', {'object_list': resources})

### SLACK ###
@csrf_exempt
@require_POST
def slack_input(request):
    data = request.body
    data = json.loads(data.decode())
    if 'challenge' in data:
        return JsonResponse({'challenge': data})
    slack_web_client.chat_postMessage(channel='#orchestrator', text=str('Message received! processing...'))
    try:
        response = slack_receiver.receive_bot_message(data)
    except RuntimeError:
        pass
    return HttpResponse(status=200)

def vuln_scan_view(request):
    # Form handle
    if request.method == 'POST':
        form = VulnerabilityScanForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['scan_type'] == 'file_target':
                vuln_scan_handler.handle_url_file(form.cleaned_data, request.FILES['input_file_name'])
            elif form.cleaned_data['scan_type'] == 'file_ip':
                vuln_scan_handler.handle_ip_file(form.cleaned_data, request.FILES['input_ip_file_name'])
            else:
                vuln_scan_handler.handle(form.cleaned_data)
            return redirect('/')
    form = VulnerabilityScanForm()
    return render(request, 'Orchestrator/vulnerability_scan_form.html', {'form': form})

@csrf_exempt
@require_POST
def one_shot_scan(request):
    if request.method == 'POST':
        scan = json.loads(request.body)
        if scan['scan_type'] == 'file_target' or scan['scan_type'] == 'file_ip':
            vuln_scan_handler.handle_url_ip(scan)
        else:
            vuln_scan_handler.handle(scan)
        return JsonResponse({'message': 'Running scan'})
    return JsonResponse({'message': 'Bad format json'})

Orchestrator/OrchestratorApp/templates/Orchestrator/base.html
<!DOCTYPE html>
<html>
<title>Orchestrator</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<body>
<!-- Side Navigation -->
<nav class="w3-sidebar w3-bar-block w3-card w3-animate-left w3-center" style="display:none" id="mySidebar">
  <h1 class="w3-xxxlarge w3-text-theme">Options</h1>
  <button class="w3-bar-item w3-button" onclick="w3_close()">Close <i class="fa fa-remove"></i></button>
  <a href="{% url 'OrchestratorApp:vulnerability_scan' %}" class="w3-bar-item w3-button">Vulnerability Scan</a>
  <a href="{% url 'OrchestratorApp:recon' %}" class="w3-bar-item w3-button">Recon</a>
  <a href="{% url 'OrchestratorApp:workspaces' %}" class="w3-bar-item w3-button">Workspaces</a>
  <a href="{% url 'OrchestratorApp:vulnerabilities' %}" class="w3-bar-item w3-button">Vulnerabilities</a>
</nav>

<!-- Header -->
<header class="w3-container w3-theme w3-padding" id="myHeader">
  <i onclick="w3_open()" class="fa fa-bars w3-xlarge w3-button w3-theme"></i>
  <div class="w3-center">
  <!---<h4>BEAUTIFUL RESPONSIVE WEB SITES</h4>-->
  <h1 class="w3-xxxlarge w3-animate-bottom">Orchestrator</h1>
    <div class="w3-padding-32">
      <!---button class="w3-btn w3-xlarge w3-dark-grey w3-hover-light-grey" onclick="document.getElementById('id01').style.display='block'" style="font-weight:900;">Handerllon</button--->
    </div>
  </div>
</header>



<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->
<script>
// Side navigation
function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "100%";
  x.style.fontSize = "40px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

// Tabs
function openCity(evt, cityName) {
  var i;
  var x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  var activebtn = document.getElementsByClassName("testbtn");
  for (i = 0; i < x.length; i++) {
    activebtn[i].className = activebtn[i].className.replace(" w3-dark-grey", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-dark-grey";
}

var mybtn = document.getElementsByClassName("testbtn")[0];
mybtn.click();

// Accordions
function myAccFunc(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Slideshows
var slideIndex = 1;

function plusDivs(n) {
  slideIndex = slideIndex + n;
  showDivs(slideIndex);
}

function showDivs(n) {
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  x[slideIndex-1].style.display = "block";
}

showDivs(1);

// Progress Bars
function move() {
  var elem = document.getElementById("myBar");
  var width = 5;
  var id = setInterval(frame, 10);
  function frame() {
    if (width == 100) {
      clearInterval(id);
    } else {
      width++;
      elem.style.width = width + '%';
      elem.innerHTML = width * 1  + '%';
    }
  }
}
</script>
</body>
</html>

Orchestrator/OrchestratorApp/templates/Orchestrator/generalTemplate.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<body>





<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->
<script>
// Side navigation
function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "100%";
  x.style.fontSize = "40px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

// Tabs
function openCity(evt, cityName) {
  var i;
  var x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  var activebtn = document.getElementsByClassName("testbtn");
  for (i = 0; i < x.length; i++) {
    activebtn[i].className = activebtn[i].className.replace(" w3-dark-grey", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-dark-grey";
}

var mybtn = document.getElementsByClassName("testbtn")[0];
mybtn.click();

// Accordions
function myAccFunc(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Slideshows
var slideIndex = 1;

function plusDivs(n) {
  slideIndex = slideIndex + n;
  showDivs(slideIndex);
}

function showDivs(n) {
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  x[slideIndex-1].style.display = "block";
}

showDivs(1);

// Progress Bars
function move() {
  var elem = document.getElementById("myBar");
  var width = 5;
  var id = setInterval(frame, 10);
  function frame() {
    if (width == 100) {
      clearInterval(id);
    } else {
      width++;
      elem.style.width = width + '%';
      elem.innerHTML = width * 1  + '%';
    }
  }
}
</script>

</body>
</html>

Orchestrator/OrchestratorApp/templates/Orchestrator/recon_view.html
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<body>

{% block content %}
    <h2>New recon scan</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Run</button>
    </form>
{% endblock %}



<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->
<script>
// Side navigation
function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "100%";
  x.style.fontSize = "40px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

// Tabs
function openCity(evt, cityName) {
  var i;
  var x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  var activebtn = document.getElementsByClassName("testbtn");
  for (i = 0; i < x.length; i++) {
    activebtn[i].className = activebtn[i].className.replace(" w3-dark-grey", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-dark-grey";
}

var mybtn = document.getElementsByClassName("testbtn")[0];
mybtn.click();

// Accordions
function myAccFunc(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Slideshows
var slideIndex = 1;

function plusDivs(n) {
  slideIndex = slideIndex + n;
  showDivs(slideIndex);
}

function showDivs(n) {
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  x[slideIndex-1].style.display = "block";
}

showDivs(1);

// Progress Bars
function move() {
  var elem = document.getElementById("myBar");
  var width = 5;
  var id = setInterval(frame, 10);
  function frame() {
    if (width == 100) {
      clearInterval(id);
    } else {
      width++;
      elem.style.width = width + '%';
      elem.innerHTML = width * 1  + '%';
    }
  }
}
</script>

</body>
</html>

Orchestrator/OrchestratorApp/templates/Orchestrator/single_vulns_view.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<body>
<div class="w3-container">
  <hr>
  <div class="w3-center">
      <!---
    <h2>Tables</h2>
    <p w3-class="w3-large">Don't worry. W3.CSS takes care of your tables.</p>
    --->
  </div>
    <form method="POST" class="post-form">{% csrf_token %}
        <div class="w3-container">
            <button class="w3-btn w3-theme" type="submit">Download csv file</button>
        </div>
    </form>
<div class="w3-responsive w3-card-4">
<table class="w3-table w3-striped w3-bordered">
<thead>
<tr class="w3-theme">
        <th>Target</th>
        <th>Affected resource</th>
        <th>Vulnerability</th>
        <th>Language</th>
        <th>Found</th>
        <th>Last Seen</th>
</tr>
</thead>
<tbody>
    <ul>
        {% for resource in object_list %}
            <tr>
                <td>{{ resource.target_name }}</td>
                <td>{{ resource.affected_resource }}</td>
                <td>{{ resource.vulnerability_name }}</td>
                <td>{{ resource.language }}</td>
                <td>{{ resource.foud }}</td>
                <td>{{ resource.last_seen }}</td>
            </tr>
        {% endfor %}
    </ul>
</tbody>
</table>
</div>

<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->
<script>
// Side navigation
function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "100%";
  x.style.fontSize = "40px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

// Tabs
function openCity(evt, cityName) {
  var i;
  var x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  var activebtn = document.getElementsByClassName("testbtn");
  for (i = 0; i < x.length; i++) {
    activebtn[i].className = activebtn[i].className.replace(" w3-dark-grey", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-dark-grey";
}

var mybtn = document.getElementsByClassName("testbtn")[0];
mybtn.click();

// Accordions
function myAccFunc(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Slideshows
var slideIndex = 1;

function plusDivs(n) {
  slideIndex = slideIndex + n;
  showDivs(slideIndex);
}

function showDivs(n) {
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  x[slideIndex-1].style.display = "block";
}

showDivs(1);

// Progress Bars
function move() {
  var elem = document.getElementById("myBar");
  var width = 5;
  var id = setInterval(frame, 10);
  function frame() {
    if (width == 100) {
      clearInterval(id);
    } else {
      width++;
      elem.style.width = width + '%';
      elem.innerHTML = width * 1  + '%';
    }
  }
}
</script>

</body>
</html>

Orchestrator/OrchestratorApp/templates/Orchestrator/vulns_view.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<body>

<div class="w3-half">
<div class="w3-card-4 w3-container">
<h2>Workspaces</h2>
<ul class="w3-ul w3-margin-bottom">
  <ul>
{% for workspace in object_list %}
    <li><a href="{% url 'OrchestratorApp:project_vulns' workspace %}">{{ workspace }}</a></li>
{% empty %}
    <li>No workspaces yet.</li>
{% endfor %}
</ul>
</ul>
</div>
</div>

<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->
<script>
// Side navigation
function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "100%";
  x.style.fontSize = "40px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

// Tabs
function openCity(evt, cityName) {
  var i;
  var x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  var activebtn = document.getElementsByClassName("testbtn");
  for (i = 0; i < x.length; i++) {
    activebtn[i].className = activebtn[i].className.replace(" w3-dark-grey", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-dark-grey";
}

var mybtn = document.getElementsByClassName("testbtn")[0];
mybtn.click();

// Accordions
function myAccFunc(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Slideshows
var slideIndex = 1;

function plusDivs(n) {
  slideIndex = slideIndex + n;
  showDivs(slideIndex);
}

function showDivs(n) {
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  x[slideIndex-1].style.display = "block";
}

showDivs(1);

// Progress Bars
function move() {
  var elem = document.getElementById("myBar");
  var width = 5;
  var id = setInterval(frame, 10);
  function frame() {
    if (width == 100) {
      clearInterval(id);
    } else {
      width++;
      elem.style.width = width + '%';
      elem.innerHTML = width * 1  + '%';
    }
  }
}
</script>

</body>
</html>

Orchestrator/OrchestratorApp/templates/Orchestrator/workspaces_view.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
<body>

<div class="w3-half">
<div class="w3-card-4 w3-container">
<h2>Workspaces</h2>
<ul class="w3-ul w3-margin-bottom">
  <ul>
{% for workspace in object_list %}
    <li><a href="{% url 'OrchestratorApp:workspace' workspace %}">{{ workspace }}</a></li>
{% empty %}
    <li>No workspaces yet.</li>
{% endfor %}
</ul>
</ul>
</div>
</div>

<!-- Script for Sidebar, Tabs, Accordions, Progress bars and slideshows -->
<script>
// Side navigation
function w3_open() {
  var x = document.getElementById("mySidebar");
  x.style.width = "100%";
  x.style.fontSize = "40px";
  x.style.paddingTop = "10%";
  x.style.display = "block";
}
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}

// Tabs
function openCity(evt, cityName) {
  var i;
  var x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  var activebtn = document.getElementsByClassName("testbtn");
  for (i = 0; i < x.length; i++) {
    activebtn[i].className = activebtn[i].className.replace(" w3-dark-grey", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-dark-grey";
}

var mybtn = document.getElementsByClassName("testbtn")[0];
mybtn.click();

// Accordions
function myAccFunc(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Slideshows
var slideIndex = 1;

function plusDivs(n) {
  slideIndex = slideIndex + n;
  showDivs(slideIndex);
}

function showDivs(n) {
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length} ;
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  x[slideIndex-1].style.display = "block";
}

showDivs(1);

// Progress Bars
function move() {
  var elem = document.getElementById("myBar");
  var width = 5;
  var id = setInterval(frame, 10);
  function frame() {
    if (width == 100) {
      clearInterval(id);
    } else {
      width++;
      elem.style.width = width + '%';
      elem.innerHTML = width * 1  + '%';
    }
  }
}
</script>

</body>
</html>